#!/usr/bin/env python
"""
This program takes the text from the Wikipedia pages and generates tuples
These tuples will form the training set
"""
import wikipedia

def get_page(f, page):
    print "WIKIPAGE: " + page
    f.write("WIKIPAGE: " + page + "\n")
    text = wikipedia.WikipediaPage(page).content.encode('ascii', 'xmlcharrefreplace')
    f.write(text)
    f.write('\n')

def main():
    filename = 'math-topics.download.raw.dat'
    f = open(filename, 'a')
    """
    get_page(f, "Absolute value (algebra)")
    get_page(f, "Absolute value")
    get_page(f, "Addition and Subtraction")
    #get_page(f, "Addition and subtraction")
    get_page(f, "Addition")
    get_page(f, "Subtraction")
    get_page(f, "Algebraic equation")
    get_page(f, "Algebraic expression")
    get_page(f, "Algebraic fraction")
    get_page(f, "Algebraic function")
    get_page(f, "Analytic geometry")
    get_page(f, "Angle")
    get_page(f, "Angles")
    get_page(f, "Area")
    get_page(f, "Arithmetic progression")
    get_page(f, "Arithmetico-geometric sequence")
    get_page(f, "Bar chart")
    get_page(f, "Base (exponentiation)")
    get_page(f, "Box plot")
    get_page(f, "Cartesian coordinate system")
    get_page(f, "Central tendency")
    get_page(f, "Circle graph")
    get_page(f, "Circle")
    get_page(f, "Circumference")
    get_page(f, "Combination")
    get_page(f, "Common Data Representation")
    get_page(f, "Common logarithm")
    get_page(f, "Complex number")
    get_page(f, "Computation")
    get_page(f, "Cone")
    get_page(f, "Congruence (geometry)")
    get_page(f, "Convex and concave polygons")
    get_page(f, "Coordinate system")
    get_page(f, "Cramers rule")
    get_page(f, "Critical point (mathematics)")
    get_page(f, "Cylinder (geometry)")
    get_page(f, "Data (computing)")
    get_page(f, "Determinant")
    get_page(f, "Diagonal matrix")
    #get_page(f, "Dilation")
    get_page(f, "Scaling (geometry)")
    get_page(f, "Discrete logarithm")
    #get_page(f, "Dispersion") SKIPPED
    get_page(f, "Distance from a point to a line")
    get_page(f, "Distance")
    get_page(f, "Elementary algebra")
    get_page(f, "Equilateral triangle")
    get_page(f, "Estimation theory")
    get_page(f, "Estimation")
    get_page(f, "Evaluation function")
    get_page(f, "Event (probability theory)")
    get_page(f, "Exploratory data analysis")
    get_page(f, "Exponential function")
    get_page(f, "Exponentiation")
    get_page(f, "Expression (mathematics)")
    get_page(f, "Factorization of polynomials")
    get_page(f, "Factorization")
    get_page(f, "Fraction (mathematics)")
    get_page(f, "Function (mathematics)")
    get_page(f, "Functional equation")
    get_page(f, "Geometric progression")
    get_page(f, "Geometric transformation")
    get_page(f, "Geometry")
    get_page(f, "Hypotenuse")
    get_page(f, "Imaginary number")
    get_page(f, "Imaginary unit")
    get_page(f, "Inequality (mathematics)")
    get_page(f, "Inverse function")
    get_page(f, "Irreducible polynomial")
    get_page(f, "Leibniz formula for determinants")
    get_page(f, "Line (geometry)")
    get_page(f, "Line chart")
    get_page(f, "Line graph")
    get_page(f, "Line segment")
    get_page(f, "Linear discriminant analysis")
    get_page(f, "Linear equation")
    get_page(f, "Linear inequality")
    get_page(f, "List of inequalities")
    get_page(f, "List of logarithmic identities")
    get_page(f, "Logarithm")
    get_page(f, "Logarithmic norm")
    get_page(f, "Logarithmic number system")
    get_page(f, "Mathematical constants and functions")
    get_page(f, "Matrix (mathematics)")
    get_page(f, "Methods of computing square roots")
    get_page(f, "Multiplication algorithm")
    get_page(f, "Napierian logarithm")
    get_page(f, "Natural logarithm")
    get_page(f, "Nth root")
    get_page(f, "Operation (mathematics)")
    #get_page(f, "Operation")
    get_page(f, "Order of operations")
    get_page(f, "Order of precedence")
    get_page(f, "Ordered pair")
    get_page(f, "Outcome (probability)")
    get_page(f, "Parallel (geometry)")
    get_page(f, "Perimeter")
    get_page(f, "Permutation")
    get_page(f, "Perpendicular")
    get_page(f, "Piecewise linear function")
    #get_page(f, "Piecewise linear")
    get_page(f, "Piecewise linear curve")
    get_page(f, "Piecewise linear function")
    get_page(f, "Platonic solid")
    get_page(f, "Polygon")
    get_page(f, "Polynomial arithmetic")
    get_page(f, "Polynomial long division")
    get_page(f, "Polynomial")
    #get_page(f, "Precedence")
    get_page(f, "Order of Precedence")
    get_page(f, "Prism (geometry)")
    get_page(f, "Prism")
    get_page(f, "Probability density function")
    get_page(f, "Probability distribution function")
    get_page(f, "Probability distribution")
    get_page(f, "Probability theory")
    get_page(f, "Probability")
    get_page(f, "Proportionality (mathematics)")
    #get_page(f, "Proportionality") SKIPPED
    get_page(f, "Pyramid (geometry)")
    get_page(f, "Pythagorean theorem")
    get_page(f, "Pythagorean trigonometric identity")
    get_page(f, "Quadratic equation")
    get_page(f, "Quadratic formula")
    get_page(f, "Quadratic function")
    get_page(f, "Quadratic programming")
    get_page(f, "Quadratics")
    get_page(f, "Quartic function")
    #get_page(f, "Rate")
    get_page(f, "Rate (mathematics)")
    get_page(f, "Ratio")
    get_page(f, "Rational function")
    get_page(f, "Rational number")
    get_page(f, "Rationalisation (mathematics)")
    get_page(f, "Real line")
    get_page(f, "Real number")
    get_page(f, "Recurrence relation")
    get_page(f, "Reduction (mathematics)")
    #get_page(f, "Reflections") SKIPPED
    get_page(f, "Regular polygon")
    get_page(f, "Rotation (mathematics)")
    get_page(f, "Rule-based system")
    get_page(f, "Sample (statistics)")
    get_page(f, "Sampling error")
    get_page(f, "Scientific notation")
    #get_page(f, "Series")
    get_page(f, "Series (mathematics)")
    get_page(f, "Shape")
    get_page(f, "Similarity (geometry)")
    get_page(f, "Slope")
    get_page(f, "Space (mathematics)")
    get_page(f, "Sparse matrix")
    get_page(f, "Sphere")
    get_page(f, "Square Roots")
    get_page(f, "Square matrix")
    get_page(f, "Square root")
    get_page(f, "Statistical dispersion")
    get_page(f, "Statistics")
    get_page(f, "Stem-and-leaf display")
    get_page(f, "Step function")
    get_page(f, "Structured data analysis (statistics)")
    """
    # get_page(f, "Structured data analysis") SKIPPED
    get_page(f, "Surface area")
    get_page(f, "System of linear equations")
    get_page(f, "System of polynomial equations")
    get_page(f, "Tangent")
    get_page(f, "Three-dimensional space")
    get_page(f, "Translations")
    get_page(f, "Transversal (geometry)")
    get_page(f, "Triangle")
    get_page(f, "Trigonometric functions")
    get_page(f, "Trigonometry")
    get_page(f, "Two-dimensional graph")
    get_page(f, "Two-dimensional space")
    get_page(f, "Venn diagram")
    get_page(f, "Vertex (geometry)")
    get_page(f, "Volume")
    get_page(f, "Zero of a function")
    f.close

if __name__ == '__main__':
    main()
